### ISSUE TITLE
git repo not available

### ISSUE THREAD

**Issue by phil123456** [rekado/lv2-mdaMetaPiano#7]
Hi rekado,

I dont really know how to contact you for this 

https://git.elephly.net/software/lv2-mdametapiano **gives a error 504**

is it gonna be up again ? I have an old version of mda/piano code but I would like to have the latest updates

thanks
Phil

**Comment by rekado** [comment]
Thanks for letting me know.  I gave the service a kick.
I haven't touched this project in many years.  You're probably better off with this project https://gitlab.com/drobilla/mda-lv2

**Comment by phil123456** [comment]
so s it the same source or  ?

**Comment by phil123456** [comment]
if anyone is interested, I made a post on how to quickly setup LV2 piano plugin with Jack on a RPI4

https://blog.philippeflorent.be/index.php/2023/07/16/emulate-piano-on-raspberry-pi-with-mda-lv2-pluggin/
